FROM debian:trixie

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    ccache \
    cmake \
    ninja-build \
    pkgconf \
    qt6-base-dev \
    qt6-wayland-dev \
    wayland-protocols \
    liblayershellqtinterface-dev \
  && rm -rf /var/lib/apt/lists/*

ENV CCACHE_DIR=/root/.ccache
ENV CCACHE_MAXSIZE=1G

WORKDIR /workspace
